### ISSUE TITLE
Use gitee from china

### ISSUE THREAD

**Issue by Kerinlin** [1995parham/github-do-not-ban-us#1010]
https://gitee.com/

**Comment by 1995parham** [comment]
@Kerinlin Thanks for introducing this alternative

**Comment by xtlsoft** [comment]
Don't use gitee. It may track your privacy data. Use your own deployed Git server.

**Comment by a764934018** [comment]
> Don't use gitee. It may track your privacy data. Use your own deployed Git server.

If you are afraid to expose privacy then you shouldn't use all online git services including github. So what are we protesting here when US banned us from using github.

**Comment by ThunderLT** [comment]
@xtlsoft  so you are being tracked by USA goverment just like Edward Snowden

**Comment by DricHao** [comment]
> Don't use gitee. It may track your privacy data. Use your own deployed Git server.

你有点蠢....

**Comment by 1995parham** [comment]
Does gitee have an English version?

**Comment by a764934018** [comment]
> Does gitee have an English version?

Yes, it has. You can switch to English by click "English" button in the bottom right corner of the page.

**Comment by Kerinlin** [comment]
> Does gitee have an English version?

Yes,that's the English version, https://gitee.com/language/en

**Comment by 1995parham** [comment]
Again thanks for introducing this service. I created an account on Gitee and I am trying to get familiar with it. I have closed this issue and add Gitee as an alternative on README.
