### ISSUE TITLE
Establish a new source code share platform controlled by UN.

### ISSUE THREAD

**Issue by daniellocust** [1995parham/github-do-not-ban-us#1042]

**Comment by mmahmoudian** [comment]
Duplicate. [This issue is suggested here](https://github.com/1995parham/github-do-not-ban-us/issues/1033#issue-473887613) already

**Comment by Dylan-TW** [comment]
But UN may be controlled by some country/ies

**Comment by Alir3z4** [comment]
WTF UN gonna do here, Iranian are not some poor hungry lifeless units that UN will shed some help on them, what's next ? getting under umbrella of UNICEF ?

btw, you can't find more corrupted than UN on planet earth and probably for in all other galaxies :D

**Comment by ovflowd** [comment]
@Alir3z4 hahahaah I laughed, you're so damn true.

Let's ask for the aliens of area 51 to do that for us.

But being serious, UN looks initially a good idea, but UN needs to be neutral, and creating a sharing platform that allow "banned countries" to be "hosted", that would look bad for UN in the international politics.

Donald Trump bullsheee you know 😅
