### ISSUE TITLE
Add Nuxt to the list of "made by Iranian developers"

### ISSUE THREAD

**Issue by erfansahaf** [1995parham/github-do-not-ban-us#107]
You missed a popular JS project, Nuxt.js with 21K stars! Its author is another Iranian, Pooya Parsa ([@pi0](https://github.com/pi0)). This guy is an active contributor in Vue.js community.

Please add this project to the list of "Made by Iranian developers".

**Comment by pesehr** [comment]
Pooya is a key developer in this project but I'm not sure that the project is made by him.

**Comment by erfansahaf** [comment]
His profile title is Author of @nuxtjs

**Comment by parsa-script** [comment]
@erfansahaf 
And this good DM :(. https://github.com/persepolisdm/persepolis

**Comment by erfansahaf** [comment]
@parsa-script Perspolis DM is already on the list.
