### ISSUE TITLE
Support and one idea

### ISSUE THREAD

**Issue by smoqadam** [1995parham/github-do-not-ban-us#11]
First of all, nicely done. This is the thing we need right now. My account is not affected as I'm not in Iran right now, but you guys have all my support and please let me know if you need any help.

And one idea, isn't it better to change the following sentence: 

> I think having a simple Github page is our fundamental right.

because IMO, it's not exactly our fundamental right.

Thanks

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
