### ISSUE TITLE
Media coverage

### ISSUE THREAD

**Issue by Hameds** [1995parham/github-do-not-ban-us#1180]
- [https://techcrunch.com/2019/07/29/github-ban-sanctioned-countries/](https://techcrunch.com/2019/07/29/github-ban-sanctioned-countries/)
- [https://www.businessinsider.com/microsoft-owned-github-reportedly-blocking-people-in-crimea-iran-sanction-2019-7](https://www.businessinsider.com/microsoft-owned-github-reportedly-blocking-people-in-crimea-iran-sanction-2019-7)
- [https://www.theverge.com/2019/7/29/8934694/github-us-trade-sanctions-developers-restricted-crimea-cuba-iran-north-korea-syria](https://www.theverge.com/2019/7/29/8934694/github-us-trade-sanctions-developers-restricted-crimea-cuba-iran-north-korea-syria)
- [https://www.theregister.co.uk/2019/07/29/github_block/](https://www.theregister.co.uk/2019/07/29/github_block/)
- [https://www.zdnet.com/article/github-starts-blocking-developers-in-countries-facing-us-trade-sanctions/](https://www.zdnet.com/article/github-starts-blocking-developers-in-countries-facing-us-trade-sanctions/)
- [https://financialtribune.com/articles/sci-tech/99111/github-bans-iran-based-users](https://financialtribune.com/articles/sci-tech/99111/github-bans-iran-based-users)

**Comment by pesehr** [comment]
Someone, please make a pr.

**Comment by alifarazz** [comment]
I'm on it. #1220

**Comment by pesehr** [comment]
Thank you!
