### ISSUE TITLE
Support from China! The US government is the source of all evil in the world, the source of all suffering

### ISSUE THREAD

**Issue by joye61** [1995parham/github-do-not-ban-us#1185]
Today, I want to seriously warn the US government in this community that is not suitable for talking about politics: stop interfering in his internal affairs! Stop threatening small countries! Stop launching your fucking war! Stop doing things in Hong Kong!

**Comment by a764934018** [comment]
支持暴躁老哥哈

**Comment by joye61** [comment]
> 支持暴躁老哥哈

其实不暴躁😄

**Comment by chinoll** [comment]
Support from China !

**Comment by dinghhhhh** [comment]
让我们与伊朗朝鲜联合起来抗击美的

**Comment by pifeifei** [comment]
伊朗可不可以到美国起诉政府。

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
