### ISSUE TITLE
来自中国的支持，技术无国界

### ISSUE THREAD

**Issue by xiaoyu824873** [1995parham/github-do-not-ban-us#1252]

**Comment by dinghhhhh** [comment]
但码农有国界，身为中国人抵制资本主义github,改用社会主义CSDN,只要充钱就能下载

**Comment by OliverXie2016** [comment]
用gitlab不就行了

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
