### ISSUE TITLE
🇺🇸US政府是万恶之源

### ISSUE THREAD

**Issue by Vibing** [1995parham/github-do-not-ban-us#1291]
美国政府一直想统一世界，然鹅却不知道自己一直在作死。
瞎搞贸易战，干预台湾，干预香港，挑拨离间。

美国很多很好的公司迫于政府压力，无奈做出让人难受的举动 大家能理解，但请在行动前给予提示报警！

美国本来就是负债大国，没有雄厚的历史底蕴，天天挑唆，也不敢打？

**Comment by hldh214** [comment]
兄弟求群号 有钱一起赚

**Comment by OliverXie2016** [comment]
哈哈哈哈

**Comment by neruthes** [comment]
头像眼熟

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
