### ISSUE TITLE
Support from Hong Kong

### ISSUE THREAD

**Issue by stevefan1999-personal** [1995parham/github-do-not-ban-us#1301]
I'm not trying to be political since we are all programmers and so should be logical but, yes, US hates Iran because of its friendship to Israel & UAE, and yes, Iran is heavily sanctioned by US, threaten to start a war with, and US tried to propagated this as an international issue (and so a smoke screen to justify US's bully) by abusing its power of world order, but what GitHub has done is morally wrong: instead of just push the user and their valuable asset out in a clean & nice bundle and tell them to not come back again until the storm has eradicated, GitHub chose to hold them hostage and lurk their original owner to open their code instead.

Let alone the ICE scandal Microsoft has got into, this could be really a bad year for both GH and MS, for another boycott & exodus to GitLab. Also, this just revealed that US is really just as shitty as China in terms of business environment advocating for self-censorship.

**Comment by wangwanchao** [comment]
I am Chinese. If I don't offend you, I think you are Chinese. Of course,  in certain aspects, self-censorship is too strict to disgusting.Hope the world be better!

**Comment by pifeifei** [comment]
> I am Chinese. If I don't offend you, I think you are Chinese. Of course, in certain aspects, self-censorship is too strict to disgusting.Hope the world be better!


The programmer is rigorous.

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
