### ISSUE TITLE
Support from China, North Korea and Taliban!

### ISSUE THREAD

**Issue by dinghhhhh** [1995parham/github-do-not-ban-us#1307]
Boycott US ！ including any American products！

**Comment by iwind** [comment]
Silly and stupid man, China is not N and T.

**Comment by dinghhhhh** [comment]
> Silly and stupid man, China is not N and T.

China, of course, is not DPRK or Taliban, but they have the same enemy US.
They should fight together, including Iran.

**Comment by mahdi-ninja** [comment]
@iwind don't feed the troll
