### ISSUE TITLE
Crimea is also blocked!

### ISSUE THREAD

**Issue by loveorigami** [1995parham/github-do-not-ban-us#1388]
I am from Crimea and I am also have blocked message.

In private repo - is my open progect LoveOrigami
http://www.loveorigami.info/oriwiki

It is World origami catalog - not weapon, not nuclear...

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
