### ISSUE TITLE
This is a support from Philipines

### ISSUE THREAD

**Issue by DricHao** [1995parham/github-do-not-ban-us#1424]
Friends of Iran have rights be here, fuckin US government, rather than github group.

**Comment by pesehr** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.

**Comment by DricHao** [comment]
> Thanks for your support
> We are really glad that you support us from your country.
> Please support us by sharing this repository and #githubforeveryone.

Sure, I will share this repository to my fackbook. well done! dude, let people realize the American freedom is so shit fake.
