### ISSUE TITLE
Update Github to GitHub

### ISSUE THREAD

**Issue by lipis** [1995parham/github-do-not-ban-us#1444]

**Comment by pesehr** [comment]
Please make a PR

**Comment by lipis** [comment]
Somebody has to edit the image..

**Comment by lipis** [comment]
Also in the description of this project.. it's embarrassing :)

**Comment by 1995parham** [comment]
@lipis I have updated the description.

**Comment by lipis** [comment]
No only the main image is left...

**Comment by lipis** [comment]
No.. all good!

**Comment by pesehr** [comment]
@lipis Tnx 👍
