### ISSUE TITLE
Support from X

### ISSUE THREAD

**Issue by ovflowd** [1995parham/github-do-not-ban-us#1593]
Could we create a Bot were we could add our Name and Country to the support list?

I think it's cleaner than just creating issues, right? 😅

Anyways, support from Germany and Brazil 🌈

**Comment by zwipyf** [comment]
Support from China as a fresh guy in GitHub

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
