### ISSUE TITLE
微软和特朗普和美国有点可笑呀！

### ISSUE THREAD

**Issue by matrix3d** [1995parham/github-do-not-ban-us#175]
总是滥用一些权利。github是世界的，又不是美国的。
美国人自大的以为啥东西都是自己的吗？！
如果这样的话,中国的gitee.com欢迎伊朗人。
美国很疯狂。
疯狂的终点就是死亡。

**Comment by Simakeng** [comment]
If Github can ban Iranian users' accounts according to US law, then it can do the same for Chinese users. The recent China-US relationship has made me really worried that this will happen.
如果Github可以根据美国法律封禁伊朗用户的账号，那么他也可以对中国的用户这么做。最近的中美关系让我真的担心会发生这种情况。

**Comment by matrix3d** [comment]
川普很疯狂。禁止就禁吧。大不了回归gitee，从此彻底和美国断绝关系。这东西，没必要去奢求什么。
就比如2个人的关系。一个人不想和你玩。那就自己去玩好了。多说无益。

**Comment by matrix3d** [comment]
。。美国屏蔽伊朗了。敢不敢屏蔽中国，求屏蔽 。有没有这个胆量。

**Comment by gitors** [comment]
唐纳德·特朗普 就是一个商人，总是一些商人的思维，根本就不配作为一个国家领导人……

**Comment by BingLingGroup** [comment]
gitee还是算了，自建吧

**Comment by BingLingGroup** [comment]
> If Github can ban Iranian users' accounts according to US law, then it can do the same for Chinese users. The recent China-US relationship has made me really worried that this will happen.
> 如果Github可以根据美国法律封禁伊朗用户的账号，那么他也可以对中国的用户这么做。最近的中美关系让我真的担心会发生这种情况。

我感觉是根据注册地IP来进行的限制，据我所知不少github中文用户注册时的IP未必是中国IP。
当然天下没有免费的午餐，丧钟为所有人而鸣。

**Comment by xtlsoft** [comment]
I think American won't dare to ban China.
If it does this, our government may start a war...

-------

Also, gitee.com isn't a good choice because CSDN is the runner and it's not worth your trust. Self-deployed Gogs may be a better choice and Git should be de-centered.

**Comment by matrix3d** [comment]
美国不禁止中国的原因是，中国的16亿人口，占世界很大比率的开发者。
少了中国的开发者，github是不完整的。
既然美国禁止了中国开发者。中国政府也不会做出任何反应。还记得中国政府自己墙了github吗。中国政府不会关心一个网站是否对中国开放。

**Comment by xtlsoft** [comment]
Thanks. Your view is good. But I don't agree the government won't take actions. The last time was because GitHub refused to give the data to the government, but now it is Microsoft.

Also, use English may make it easier to understand for open-source lovers from all over the world.

**Comment by scvoet** [comment]
当 GitHub 彻底被美国所限制后，群众将会缔造一个崭新的、自由的新平台。自始至终 GitHub 都不是我们唯一的选择，我们会用自己的方式拥抱我们想要的一切

When GitHub is completely restricted by the United States, the masses will create a new, free and new platform. GitHub is not our only choice from start to finish, we will embrace everything we want in our own way.

**Comment by upupming** [comment]
I think any commercial company cannot avoid politics, but the way they deal with these stuff matters. I really appreciate GitHub before it was acquired by Microsoft, it as least will notify its users to these things, such as https://github.com/github/gov-takedowns. But now we can see, it is truly far from those days.

This event makes me think about "IEEE bans Huawei reviewers", Iran developers are equal and we should respect their awesome works on GitHub, OpenSource won't exist without equality! Hope GitHub will give us a positive answer.

**Comment by iwind** [comment]
> 总是滥用一些权利。github是世界的，又不是美国的。
> 美国人自大的以为啥东西都是自己的吗？！
> 如果这样的话,中国的gitee.com欢迎伊朗人。
> 美国很疯狂。
> 疯狂的终点就是死亡。

别坑外国人了，国内防火墙更厉害，我都怀疑他们能不能访问gitee。而且gitee是使用gitlab的，也是来自美国公司的产品。

人类世界有必要创建一个无政治的公共的中立区域了。

**Comment by callmesoul** [comment]
> > 总是滥用一些权利。github是世界的，又不是美国的。
> > 美国人自大的以为啥东西都是自己的吗？！
> > 如果这样的话,中国的gitee.com欢迎伊朗人。
> > 美国很疯狂。
> > 疯狂的终点就是死亡。
> 
> 别坑外国人了，国内防火墙更厉害，我都怀疑他们能不能访问gitee。而且gitee是使用gitlab的，也是来自美国公司的产品。
> 
> 人类世界有必要创建一个无政治的公共的中立区域了。

Like Facebook Libra

**Comment by dinghhhhh** [comment]
@matrix3d 抵制github，缺了中国码农GitHub就会奔溃，让美国人搬起石头砸自己的脚

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.

**Comment by YUbuntu0109** [comment]
> 
> 
> If Github can ban Iranian users' accounts according to US law, then it can do the same for Chinese users. The recent China-US relationship has made me really worried that this will happen.
> 如果Github可以根据美国法律封禁伊朗用户的账号，那么他也可以对中国的用户这么做。最近的中美关系让我真的担心会发生这种情况。

wish it don't happen · · ·
