### ISSUE TITLE
Add related articles or twits 

### ISSUE THREAD

**Issue by ShahinSorkh** [1995parham/github-do-not-ban-us#178]
Some part of me thinks it began by my [blog post](http://shahinsorkh.ir/2019/07/20/how-is-it-like-to-be-a-dev-in-iran) ([src](https://github.com/ShahinSorkh/ShahinSorkh.github.io))!

Anyways, I suggest you add a list of related similar articles/blogs or even tweets.

**Comment by BelegCuthalion** [comment]
> Anyways, I suggest you add a list of related similar articles/blogs or even twits.

There is a "Further Readings" section. Guess you can add them there.

> Some part of me thinks it began by my blog post (src)!

"it"?

**Comment by ShahinSorkh** [comment]
>"it"?

Sanctions are not a new thing, and Microsoft is the owner of github for a while. They suddenly decided to apply the sanctions.

It's just a guess, an unlikely one.

**Comment by ConnerOrth** [comment]
In the spirit of accumulating/grouping all social media and such new about this, please consider adding/sharing [https://twitter.com/conner_orth/status/1154723522729709568](https://twitter.com/conner_orth/status/1154723522729709568) aswell.
