### ISSUE TITLE
Github trending list

### ISSUE THREAD

**Issue by bluemmb** [1995parham/github-do-not-ban-us#188]
I am not sure how github trendings projects work, but I am curious to know that why this repository doesn't go to the [list](https://github.com/trending) ?

**Comment by 1995parham** [comment]
@bluemmb This is our problem too

**Comment by BelegCuthalion** [comment]
https://github.community/t5/How-to-use-Git-and-GitHub/How-github-detect-trending-repositories/td-p/5925

**Comment by upupming** [comment]
> https://github.community/t5/How-to-use-Git-and-GitHub/How-github-detect-trending-repositories/td-p/5925

Form this post, @lee-dohm Said:

> As I stated, there is logic to prevent gaming of the system. Gaming of the system isn't always or even necessarily often committed by the owner of the repository, but can also be undertaken by overenthusiastic fans of the repository, or even ... we don't describe our exact system for determining repository trends.

So are we "overenthusiastic fans"? That's a question.

**Comment by bluemmb** [comment]
@1995parham @BelegCuthalion @upupming I was thinking that if the algorithms are as such that are marking this repo as spam or something as you have shared the links, we should do something about it.

But it seems that the repo is in [list](https://github.com/trending) now. I hope we will hear more good news in next days.

Thank you guys for putting your time to do this impressive job.

**Comment by BelegCuthalion** [comment]
@bluemmb I still can't see it. Did you applied any specific filters?

**Comment by bluemmb** [comment]
@BelegCuthalion No! I checked again and it is the first one in the list too.

![Screenshot from 2019-07-28 23-21-07](https://user-images.githubusercontent.com/7195720/62011538-cf208c80-b18e-11e9-9433-87f584c38cfa.png)

**Comment by 1995parham** [comment]
@bluemmb Thank you for this good news.

**Comment by BelegCuthalion** [comment]
@bluemmb I see it now. Thanks everybody.

**Comment by BelegCuthalion** [comment]
It's weird, it produces a totally different lists.
![Screenshot from 2019-07-28 23-37-55](https://user-images.githubusercontent.com/4344100/62011972-0b56eb80-b195-11e9-87f5-cc4ea3c2945b.png)

The difference is presence this cookie named "tz". It has an interesting content.
![Screenshot from 2019-07-29 00-07-15](https://user-images.githubusercontent.com/4344100/62011984-4e18c380-b195-11e9-9711-b4affc344fb7.png)

**Comment by dou4cc** [comment]
@BelegCuthalion 

obviously "tz" means timezone. also, after changing it, my newsfeed restarted.

**Comment by BelegCuthalion** [comment]
@dou4cc Of course.

This is a kind of situation that could make anyone a little paranoid 😳😅

**Comment by dou4cc** [comment]
but simply changing timezone from Asia/Shanghai to Asia/Tehran does not trigger ban.

**Comment by dou4cc** [comment]
sorry i do not have an Iran IP address. who investigate further to determine how GitHub determines?

**Comment by bluemmb** [comment]
I manually changed the 'tz' to some different values from Europe/London, Asia/Tokio, America/Indiana/Indianapolis ... they all return the same list but for America/Los_Angeles that returns totally different list like what is in [this 2 images](https://github.com/1995parham/github-do-not-ban-us/issues/188#issuecomment-515789256).

**Comment by upupming** [comment]
It seems that GitHub is partitioning people by their timezone and here is my list from `Asia/Shanghai`:

![image](https://user-images.githubusercontent.com/24741764/62095680-b6f65d80-b2b3-11e9-8744-64d32bcfb58b.png)

**Comment by sijad** [comment]
from last night I can't see this repo in trending list anymore...

**Comment by 1995parham** [comment]
@sijad Yes, I think they remove us again
