### ISSUE TITLE
some suggets!

### ISSUE THREAD

**Issue by gharabaghi** [1995parham/github-do-not-ban-us#193]
first thank you for making this campaign.
this is a shaming act in open source world and the reason why microsoft doesn't support open source and why many developers hate this company.
i think it should be better to inform pen source founders and contributors, even those are famous.

**Comment by pesehr** [comment]
Thank you @gharabaghi 
Do you have any idea?

**Comment by gharabaghi** [comment]
another thing!
i will not star this repo until you change the  tune of the words from begging. don't humiliate iranian users.

@pesehr as i said it's shaming. and open source world should talk about this acts (it's not just about github, any company that does this action) and share their comments.

**Comment by BelegCuthalion** [comment]
@gharabaghi There was a discussion going on here #38. Do you have any suggestions?
