### ISSUE TITLE
Politics != Open Source Contribution

### ISSUE THREAD

**Issue by bluemix** [1995parham/github-do-not-ban-us#289]

**Comment by sroehrl** [comment]
Open Source == Free Speech
Free Speech == Politics

**Comment by bluemix** [comment]
you got me wrong :D
I meant that open source should not be involved with politics

**Comment by ShayBox** [comment]
GitHub is not open source, this choice was not made by github, welcome to US law, many websites are being forced to do this.

**Comment by ovflowd** [comment]
I think he meant that isn't not a good idea to create a repository about politics in a platform that is about coding.

**Comment by bluemix** [comment]
you got me wrong.
I meant, open source collaboration is free from politics,
and politics should not interfere with open source.
and I am completely supporting the repo and feeling mad about 
how GitHub is acting with Iranian (and other countries) developers.

**Comment by ovflowd** [comment]
Feel free to be mad, it wouldn't change that isn't GitHub fault.
