### ISSUE TITLE
جناب ظریف تحویل بگیر!

### ISSUE THREAD

**Issue by sparse91** [1995parham/github-do-not-ban-us#305]
فکر می کنم بهتره به جای التماس کردن به گیت هاب، دنبال معرفی و مقایسه جایگزین ها بود. این موضوع برای گیت هاب یه بحث قانونیه و مطمئنا کوتاه نمیاد.

**Comment by parsa-script** [comment]
@sparse91 اگه میشد جایگزین پیدا کرد اینکارو نمیکرد :))

**Comment by khaninejad** [comment]
قانون رو اجرا کنه باشه قبول 
ولی بهتر بود، قبلش حداقل یک اخطار میداد

**Comment by amirhz** [comment]
چرا هر چی بدبختی سر ما باید بیاد واقعا دیگه میشه گفت در مزخرفترین کشورهای دنیا زندگی میکنیم
