### ISSUE TITLE
Projects made by Iranian developers

### ISSUE THREAD

**Issue by arsalanses** [1995parham/github-do-not-ban-us#34]
![Screenshot_2019-07-26 علیرضا امیرصمیمی on Twitter arsalanse Ammir github پرسپولیس رو عمدا اضافه نکردم اصولا با انتساب یک کش (1)](https://user-images.githubusercontent.com/39537412/61962530-f0427b00-afde-11e9-9a35-f638337a4e4d.png)
https://twitter.com/AR_AmirSamimi/status/1154767945677062144

I think this list may cause misunderstanding for people :(

**Comment by 1995parham** [comment]
@alireza-amirsamimi Based on the following tweets, you want to remove Perspolis from the list of Iranian projects?

**Comment by arsalanses** [comment]
Of course not, just maybe we should add a note that we glad to share open-source projects and take part in the community as Mr. Amirsamimi said before these projects are FREE and we should avoid from the idea that these projects belong to a specific country, of course, nobody makes this mistake! but new ones may make a mistake because of "made by" in the title.
do you think this way? maybe I'm wrong I'm not sure about this

**Comment by pesehr** [comment]
@arsalanses 
Please change the title and make PR.
