### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by xtlsoft** [1995parham/github-do-not-ban-us#357]
Do you have access to Travis-CI, GitHub Actions, etc.?
And, is GitHub Applications available for you?

**Comment by xtlsoft** [comment]
And, if GitHub API is also blocked then?

**Comment by 24js** [comment]
It's available for Public Repos, But we can't do any action on Private Repo's even deleting 
I had Travis-CI but travis can't access my repositories gives ` The requested URL returned error: 403` error

**Comment by DanielRuf** [comment]
Travis CI is a german company so they do not block the users. At least I am not aware of such sanctions from our government.

**Comment by 24js** [comment]
@DanielRuf No they won't, I think xtlsoft Idea was trying to access our private repos from a third-party app which has permission to access the repo, I had Travis-CI added to my private repositories but sadly it can't access it anymore due to Github disabling my Private repos

**Comment by xtlsoft** [comment]
Right @24js got the point. And I'm thinking about building a Git repository distribution system just looks like BT. It may get permission control and is mutable then.
