### ISSUE TITLE
README.md conflicting

### ISSUE THREAD

**Issue by xtlsoft** [1995parham/github-do-not-ban-us#363]
I think at the moment the README.md is changing so quickly and all the PRs may be conflict.

So I suggest not to add information in README.md directly and let CI to generate it.

**Comment by Himself65** [comment]
‘not add infos to README.md’

so what your solution?

**Comment by 1995parham** [comment]
@xtlsoft You are right but the rate of PR is so high so we cannot even sort the supporters' list but in the next few days we will update it.
