### ISSUE TITLE
Support from Nepal

### ISSUE THREAD

**Issue by shirshak55** [1995parham/github-do-not-ban-us#368]
Nobody should be judged based on nationality. 

Code and technology don't care if its from iran or if its from china. And I always thought github was a platform for making new code and sharing technology with each other.

Github you cannot stop the technology and innovation like this.

Again github you have disappointed us :(

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
