### ISSUE TITLE
Use Alphabetical order to reduce the Merge conflicts

### ISSUE THREAD

**Issue by simon300000** [1995parham/github-do-not-ban-us#389]
I suggests we order names by alphabetical orders;
Which would reduce the conflicts.
#363 

* ❤️ Support

**Comment by xlxs4** [comment]
Someone should better automate the whole process, we need volunteers!
I am also willing to help if my help is needed

**Comment by simon300000** [comment]
I am wondering what automation I can make,
I am of course willing to help

**Comment by 1995parham** [comment]
@simon300000 We have sorted the supporters's list. If you can provide us with automation script for sort we will very happy.

**Comment by simon300000** [comment]
> @simon300000 We have sorted the supporters's list. If you can provide us with automation script for sort we will very happy.

@1995parham I made a javascript script runs on nodejs, #1455 
If node runtime environment is a problem, I can make a simpler script that runs in browser environment.
