### ISSUE TITLE
Nice Trade Trade Controls Update

### ISSUE THREAD

**Issue by 24js** [1995parham/github-do-not-ban-us#417]
25 July New Update 
25 July :boom: :fu: to Developers from 5 countries, No notice no shit 

https://web.archive.org/web/*/https://help.github.com/en/articles/github-and-trade-controls

![f9d](https://user-images.githubusercontent.com/4061327/61995952-fe0e0400-b0a3-11e9-9ae9-1b7424bc5949.gif)

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
