### ISSUE TITLE
Support from Colombia  (fuck you microsoft)

### ISSUE THREAD

**Issue by Mayccoll** [1995parham/github-do-not-ban-us#473]
yea!! ones again FUCK YOU MICROSOFT!

**Comment by ConnerOrth** [comment]
I can understand your frustration but this isn't Microsofts fault.
GitHub is a U.S. based company that has to abide by the law.
And we can only hope that Microsoft/GitHub tries to find ways to still help Iranian (and others) affected by this, with a workable solution.

The main idea behind actions such as this github repo and e.g. social media publications (such as but not limited to [https://twitter.com/conner_orth/status/1154723522729709568](https://twitter.com/conner_orth/status/1154723522729709568) is to raise awareness in hopes of finding a solution. Not to spread hatred against a company or person.

**Comment by ovflowd** [comment]
Another observation is that Microsoft doesn't control GitHub, they have 0 power to interfere.

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
