### ISSUE TITLE
I support you in your efforts to overthrow your dictator

### ISSUE THREAD

**Issue by bhartvigsen** [1995parham/github-do-not-ban-us#475]
However, I do not support you in your efforts to undermine sanctions.

**Comment by BelegCuthalion** [comment]
People here are gathered for a common cause, which is clearly stated in the README file. Any unreasonable diversion from it, specially in a divisive direction could cause this gathering to fall apart.
Thanks for your support, but not everyone here shares your opinion. (To what extent, is a matter of debate, which is not why this repo is made)

**Comment by shangjiaxuan** [comment]
> I support you in your efforts to overthrow your dictator 

Well, can I say "I support you in your efforts to overthrow Trump"? 

That's basically the same thing there. Problems or issues within a country should be handled by the people living in it, NOT some international police... These political ideas are always biased and should be thought about more thoroughly before actually taking a side.
