### ISSUE TITLE
assistance?

### ISSUE THREAD

**Issue by Darkflib** [1995parham/github-do-not-ban-us#5]
UK based here. Anything I can do to help?

**Comment by blacksrc** [comment]
I guess the best way to help is sharing this repository. It will be really appreciated.

**Comment by PurHur** [comment]
Try to avoid a non deal brexit or you are the next.

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
