### ISSUE TITLE
پرچم ایران

### ISSUE THREAD

**Issue by handinux** [1995parham/github-do-not-ban-us#555]
درست است که گیت هاب این چهار کشور رو به یک چشم دیده اما حقیقتا ایران ما شبیه سوریه و کره شمالی...نیست. لطفاً یک اینجا دست از حمایت از سوریه بردارید. بگذارید پرچم ایران تنها باشد. بگذارید مردم آن کشورها خودشان از خودشان حمایت کنند. به حال خودشان رهایشان کنید

**Comment by BelegCuthalion** [comment]
ما در حال حمایت از کشوری نیستیم، ما در حال اعتراض به یک عمل ظالمانه‌ایم. حمایت از از کشور هم یکی از نتایجِ آن است. به نظرم با بدونِ هیجان و تعصبِ بی‌دلیل، تأثیرِ این اعتراض بیشتر و نتایج‌اش هم پرثمرتر خواهد بود.

**Comment by mmsamiei** [comment]
قرار باشه این جمله بگذاریم مردم آن کشور خودشان از خودشان حمایت کنند را عمل کنیم باقی کشور‌ها هم اینطوری به این رپو که میرسند همین رو باید در حق ما تکرار کنن.
