### ISSUE TITLE
Can't you just use a VPN?

### ISSUE THREAD

**Issue by SimplyCodin** [1995parham/github-do-not-ban-us#58]
The repos are still accessible outside of Iran. Why don't you just use a vpn to download the repo? People should be trying to find ways around instead of complaining

**Comment by BelegCuthalion** [comment]
No, our accounts are flagged.

**Comment by 1995parham** [comment]
@SimplyCodin Yes, VPN is a good solution in situations like Gitlab but here Github restricts our accounts and removes our private repository in the way that we cannot get our code back.

**Comment by pesehr** [comment]
@SimplyCodin 
And also removed our Github.io pages :)))

**Comment by mmsamiei** [comment]
@SimplyCodin thanks from Google and other your kind companies always we connect using VPN! but now github blocked our private repo and even we can't download them using VPN!

**Comment by BelegCuthalion** [comment]
@SimplyCodin Even if you sign in to Github via an Iranian proxy server once, or push your code during a vacation in Iran, you should "file an appeal" to prove you are not are not Iranian.

**Comment by xtlsoft** [comment]
Can you use GitHub's API to make them public for a while and then download them then?
