### ISSUE TITLE
How to determine nationality of a user?

### ISSUE THREAD

**Issue by filipre** [1995parham/github-do-not-ban-us#606]
Hi,
the README says

>GitHub's team decided to take one step further and restrict us based on our Nationality no matter where we are living, while they were able to just restrict our IP addresses like other US-based companies.

Now I am wondering though: How does Github find out the nationality of a user if they don't use IP addresses? How would they know that I am not an Iranian for instance? Are they using mobile phone numbers, primary language of repositories or email addresses? If so, there is a high probability that non-Iranian people are affected as well. I believe that the Readme should answer this question.

**Comment by Eros** [comment]
I believe IP address will play a major factor in them blocking people and will likely be the primary source to determine who can access and who can't. I could see them using the pre-set locations on peoples profiles as something to factor in as well. Them blocking countries is going to cause issues and have flaws so I imagine that they will also have something setup to request you be unblocked as long as you can prove it. People will likely also find a way around this as well.

**Comment by dou4cc** [comment]
chinese here
just concerned on whether switching IP address prevents ban

**Comment by Eros** [comment]
@dou4cc the really bad thing here is we've been given little to no information on how they're going to be doing this, so that could really be a yes/no answer.

**Comment by filipre** [comment]
The Readme is misleading. [This](https://twitter.com/natfriedman/status/1155311123467399168) tweet from @nat says:

>The restrictions are based on place of residence and location, not on nationality or heritage. If someone was flagged in error, they can fill out a form to get the restrictions lifted on their account within hours.

So I assume, that there were simply some unjustified bans which made some believe (@1995parham) that these were based on their nationality.

**Comment by 1995parham** [comment]
Yes, they ban us based on their IP address but they refer to a long history so if a person connect to Github somewhere in his/her history from Iran they ban him/her so it makes us believe they ban us based on their nationality.

**Comment by dou4cc** [comment]
so, since [Account Reactivation Request Form](https://airtable.com/shrGBcceazKIoz6pY) requires even a copy of your photo identification (ID), a selfie and the ID number, in some ways, GitHub is right implementing real-name system slowly.

**Comment by dou4cc** [comment]
GitHub has got insane. we had better declare that and escape right now, since it is even worse than Twitter.

**Comment by filipre** [comment]
Thanks for editing the Readme. It says now

>GitHub decided to take one step further and ban every user that used Iran's IP address somewhere their history no matter where she/he is living, while they could just restrict access by IP address like other US-based companies. This action is kind of ban by nationality.

which I believe is more accurate. Also it became clear that they *do* use IP addresses so I consider my question answered :)
