### ISSUE TITLE
The only way to actually 'Support'

### ISSUE THREAD

**Issue by 0x416c69** [1995parham/github-do-not-ban-us#618]
I don't think this repo will gain us anything in the end. GitHub is an American company and they are not allowed to give up in any circumstances about applying this blocking.

Some people are angry because GitHub blocked us which we will never be able to do anything about it and come on, it's their government and country, wouldn't we do the same if our own government set these kind of limitations? I mean I wouldn't risk my company for some outsiders!

But some people are angry because GitHub blocked us without notifying us before that and they don't allow us to download our private repositories, these people are right and anyone claiming to be a human should hand us some help.

However there is a way to **actually** get support from all users in GitHub and that's making GitHub detection commit suicide and blocking all users in GitHub (But I'm not sure if everyone in GitHub will do this for us anyways, a major number of users will also do it) and that's suggesting them to backup their private repositories and use Iranian VPN to access GitHub for sometime. (I would host some free Iranian VPNs myself if people actually support this idea)

Then GitHub would have to unblock everyone and change the way of blocking and that will be IP blocking which we can bypass, it's our expertise after all this blocking from inside and outside right? 😆 

Account blocking is really lame and I think this is some kind of direct order to version control hosts.

Alternatively you can all use self-hosted GitLab.

**Comment by 1995parham** [comment]
@0x416c69 This repository is here only for informing other users and Github about the conditions that we have. I think maybe Github provide a statement about these restrictions and its future to us. Your idea is good but I think people may not support us with that.
