### ISSUE TITLE
Support from China!

### ISSUE THREAD

**Issue by shangjiaxuan** [1995parham/github-do-not-ban-us#627]
Sad thing that this has actually happened... GitHub updated its EAR agreement to state its service was under US export law, like, a month ago, and should have saw this coming, especially with the trade war thing going on around that time... I actually made [this repo](https://github.com/shangjiaxuan/Github-EAR-boycott) around that time..

Ever considered opening up an alternative smaller server? Just a suggestion...

**Comment by shangjiaxuan** [comment]
I KNEW the US politicians are up to something when the EAR agreement was updated... But still didn't see THIS coming... Outrageous...

**Comment by fakefred** [comment]
Speaking of an alternative git host: 

Why stop at *one* git host? One of the reasons why those gitlab instances hosted on various servers are not as competent as GitHub is that they **lack social functionalities**. We need a federated git community that can be out of the United States' total control, similar to mastodon.

See [my issue](https://github.com/1995parham/github-do-not-ban-us/issues/629).

Also, `support_from["china"] ++`

**Comment by liguobao** [comment]
The server computer on the US, so limits the local low.

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
