### ISSUE TITLE
GitHub supports American Imperialism. We support Your Independence.

### ISSUE THREAD

**Issue by neruthes** [1995parham/github-do-not-ban-us#643]
It is neither about finding alternatives of GitHub nor about persuading GitHub lifting the ban. It is about abolishing this American Imperialism.

I call all American people to stop this imperialist practice. By educating China the wrong way of global leadership, general American people will be those who pay the price at last. Sincerely and honestly, I hope American people can avoid suffering a sudden collapse when a graceful step-down is still possible. Don't make China the new America.

**Comment by BetaLeaf** [comment]
America would like to let you know most of us think our president is an immature bafoon and an idiot. Hope this restriction is lifted soon.

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
