### ISSUE TITLE
Make public!

### ISSUE THREAD

**Issue by TrueMoein** [1995parham/github-do-not-ban-us#666]
Now in order for bringing back our data we can make our private repositories public...

![makePublic](https://user-images.githubusercontent.com/7044050/62002088-bd999f00-b112-11e9-92cb-ec7e66bc6b1c.jpg)

**Comment by 1995parham** [comment]
@TrueMoein This is good news for us at this time.

**Comment by 1995parham** [comment]
@pesehr I think we can add this under the news section.

**Comment by Mehran** [comment]
Also, Yellow message of restriction in top of the page has been changed, unfortunately, I close it

**Comment by BelegCuthalion** [comment]
This is just an evasion! Although seeing them still made no public announcement irritates me. Moreover, now they are actually promoting **illegal activity**, by forcing probably many people to break their NDA as their only way. These kind of actions can't fool anyone, they still have things to do.

I think it should be placed somewhere to be noticed more easily, maybe topper or/and a separate file.

**Comment by ShalokShalom** [comment]
The Readme of this very repository shows a public announcement, just scroll down.

**Comment by pzk123** [comment]
希望GitHub可以很好的解决这个问题，就像我们解决我们停电1个月的问题一样。
