### ISSUE TITLE
IRAN

### ISSUE THREAD

**Issue by mortezasabihi** [1995parham/github-do-not-ban-us#679]
![2000px-Flag_of_Iran_(official) svg](https://user-images.githubusercontent.com/35567646/62002356-af9a4d00-b117-11e9-9b23-e3360bdba0f0.png)

github should be free for everyone.

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
