### ISSUE TITLE
انسانیت

### ISSUE THREAD

**Issue by Hamidnch** [1995parham/github-do-not-ban-us#683]
Hi.
The issues of Governments should not be linked to ordinary people.
The right of the Iranian people is not a disrespect.
People who already have livelihood problems.
Begging more thinking and rationalism.
We are all human, observe our minimum human rights.
**Great thanks to your former services**

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
