### ISSUE TITLE
add supports from issues to readme

### ISSUE THREAD

**Issue by motakbiri** [1995parham/github-do-not-ban-us#69]
it would be great if we add supporters from other countries in issues to the readme (with their country flag 😄 )

**Comment by 1995parham** [comment]
@motakbiri can you create a PR for this?

**Comment by motakbiri** [comment]
yeah I can do it tomorrow, if you were able to do it in the meantime, I would appreciate it.

**Comment by Uniminin** [comment]
It would be great. All the best

**Comment by motakbiri** [comment]
@1995parham https://github.com/1995parham/github-do-not-ban-us/pull/133
