### ISSUE TITLE
Support from a Dutch developer.

### ISSUE THREAD

**Issue by ConnerOrth** [1995parham/github-do-not-ban-us#7]
Just wanted to let you know that I'll be sharing this with as many fellow developers as I can find.

Greetings a Dutch Developer.

**Comment by 1995parham** [comment]
@ConnerOrth Thank you for your support.

**Comment by ConnerOrth** [comment]
https://mobile.twitter.com/conner_orth/status/1154723522729709568 if anyone wants to spread the message.

**Comment by pesehr** [comment]
Dear @ConnerOrth,

Thanks for your support.
We added a support section.

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
