### ISSUE TITLE
Support from China

### ISSUE THREAD

**Issue by 88250** [1995parham/github-do-not-ban-us#70]
> People should not be judged based on their living country.

GitHub should be more open and free, I wish you all the best.

**Comment by 1995parham** [comment]
@88250 Thank you for your support. 🙌

**Comment by SnailMann** [comment]
I hope Github will remain open and free, and not let developers lose confidence in it. Especially when you suddenly can't download your own private repository, it's very inhumane. Support from China! :punch:

**Comment by Sogrey** [comment]
Github is for everyone!
It should not be differentiated by country or region.
Support from China! 👊

**Comment by Simakeng** [comment]
If Github can ban Iranian users' accounts according to US law, then it can do the same for Chinese users. The recent China-US relationship has made me really worried that this will happen.
如果Github可以根据美国法律封禁伊朗用户的账号，那么他也可以对中国的用户这么做。最近的中美关系让我真的担心会发生这种情况。

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
