### ISSUE TITLE
Endless Support From Everyone To Iran!

### ISSUE THREAD

**Issue by Uniminin** [1995parham/github-do-not-ban-us#72]
Github has always been the greatest open source distributing platform and is meant to be used by everyone. It isn't good to see one of our beloved country called Iran is getting blocked from using github. Please #1Don't. Github?
https://github.com/Uniminin/Supporting-Iran

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
