### ISSUE TITLE
   اوپن سورس ریشه در بنیادیترین ضمیر بشر دارد   Open source have roots in the most fundamental human pronoun

### ISSUE THREAD

**Issue by majid-khosravi** [1995parham/github-do-not-ban-us#807]
دوستی دارم که سالها پیش جمله ی بالا رو لق لقه زبونش کرده بود و با این الگو هر نوع کمکی و خدمتی رو با دیگران به اشتراک می گذاشت.

در روزهای اخیر به شدت یاد این جمله می افتم  و نیز یاد این موضوع که @GitHub با این رفتارش، اندک بویی از بشریت نبرده....

**Comment by sandking** [comment]
what does it mean ?

**Comment by majid-khosravi** [comment]
> what does it mean ?

in the English:
Open source is rooted in the most fundamental human pronoun.

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
