### ISSUE TITLE
More Further Readings

### ISSUE THREAD

**Issue by hossein-pourbozorg** [1995parham/github-do-not-ban-us#833]
https://www.businessinsider.com/microsoft-owned-github-reportedly-blocking-people-in-crimea-iran-sanction-2019-7

https://appuals.com/github-has-started-blocking-developers-from-countries-that-face-us-trade-sanctions-and-restricting-access-to-the-repositorys-tools/

**Comment by 1995parham** [comment]
Thanks for the links 🙌
