### ISSUE TITLE
Use GitLab instead

### ISSUE THREAD

**Issue by mmikeww** [1995parham/github-do-not-ban-us#858]
Use GitLab instead

**Comment by Giltyhub2** [comment]
It's also based in the US

**Comment by mmikeww** [comment]
@Giltyhub2 are they censoring?

**Comment by 1995parham** [comment]
@mmikeww They just ban our IP address but we can access it with proxies.

**Comment by isolated-system** [comment]
Maybe you can use a VPN.

**Comment by mmahmoudian** [comment]
it's just a matter of time that other US-based services follow Github. After-all , they have zero income from Iran (don't know much about revenue generated by other countries of this ban). It sounds logical, at least to them, that they stick to the US regulations compared to stick to something that does not generate revenue.

The ultimate solution would be something similar to what people are discussing #629 and #1033
