### ISSUE TITLE
Support from the UK

### ISSUE THREAD

**Issue by RevoluPowered** [1995parham/github-do-not-ban-us#890]
Going to be removing all my repositories, commercial and otherwise unless these users rights are fully restored.

GitHub should be supporting these developers and also fighting back at this regulation with their own lawyers.

I am appalled that Microsoft and GitHub would do this, I will make sure that any products stay away from your company from now on and no longer adopt all of your technology stacks.

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
