### ISSUE TITLE
Suggest readers to take further action

### ISSUE THREAD

**Issue by BelegCuthalion** [1995parham/github-do-not-ban-us#9]
Add a section to README.md for what people in accord can do further to spread the word; like changing avatars, setting status or trending a hashtag on social platforms.

I set an appropriate status for example. We can coordinate these actions.

**Comment by 1995parham** [comment]
@BelegCuthalion Yes I think it is a great idea to have some status or use hashtags, can you create a PR for this?

**Comment by amirhs712** [comment]
Good idea, let me know if I can be of any help.
Also in the end, if they shut down anyway, we can start our own git system in Iran (or even other sanctioned countries).
Maybe this whole thing could be a great inspiration for all of us.

We're not terrorists, we're not some evil people, we're all **human**, whether Persian, Asian, American...

**Comment by BelegCuthalion** [comment]
Maybe a designer a could make some avatars or ribbons, and also I'm not really into social networks, so I'm not sure about the hashtag thing.
#10

**Comment by BelegCuthalion** [comment]
Also about Iranian flag, I'm not really sure now that it is a good suggestion, as it might seem just a "nationalist" problem, which is not. It is rather a "humanist" one.

**Comment by amir-yaghoobi** [comment]
@BelegCuthalion Yeah we should consider something other than the Iranian flag.

**Comment by pesehr** [comment]
@ConnerOrth, @BelegCuthalion  @amir-yaghoobi @amirhs712 
Thanks for your support and ideas.
We added a support section.
We think this is not just for Iranian people and we should show everyone developers have a powerful community.
Please read the support section and share that.

**Comment by amir-yaghoobi** [comment]
@1995parham @pesehr @amirhs712 @BelegCuthalion 
We could create a GitHub organization too.

**Comment by alirezazolanvari** [comment]
I think encouraging developers to star all other Iranian open-source projects in order to increase the number of Iranian repositories in GitHub trending lists can be helpful.

**Comment by BelegCuthalion** [comment]
@alirezazolanvari I think this is not necessary nor helpful, even it can have drawbacks. I already have [these](https://devrant.com/rants/2196018/so-my-github-account-got-restricted) people (actually Iranian) that accuse this repo "like hoarding".

**Comment by alirezazolanvari** [comment]
It's just a suggestion but actually being accused by a few persons cannot be the drawbacks of this suggestion.

**Comment by gitors** [comment]
I am a Chinese , From People's Republic of China .
 
we have our own git system in my country .  [Gitee](https://gitee.com/)

Welcome Iranian developers.

**Comment by rochakgupta** [comment]
Twitter would be a great way to spread this to a wider range of developers.

**Comment by BelegCuthalion** [comment]
@rochakgupta Of course, not only devs, it is a good way to also inform non-techy people.

I don't have an account, but it seems githubForEveryone is growing fast. Although @github and @natfriedman are yet to make the smallest reaction. And there are also real people out there who think like [this](https://twitter.com/BarryBscho/status/1155147298583785472).
![Screenshot from 2019-07-28 01-40-12](https://user-images.githubusercontent.com/4344100/61999536-ad64ce00-b0d8-11e9-9de8-defdcaf5e79a.png)

**Comment by BelegCuthalion** [comment]
> also the UN
is a one big stinking lie. People being ignorant enough for such a nonsense to be said without any concern about being questioned is why I'm here. That's why we should let them know.

**Comment by rochakgupta** [comment]
> @rochakgupta Of course, not only devs, it is a good way to also inform non-techy people.
> 
> I don't have an account, but it seems githubForEveryone is growing fast. Although github and natfriedman accounts are yet to make the smallest reaction. And there are also real people out there who think like
> ![Screenshot from 2019-07-28 01-40-12](https://user-images.githubusercontent.com/4344100/61999598-59f37f80-b0da-11e9-964f-05904afa6610.png)

Well, nobody can reason with those kinds of users. We can try creating a post on Reddit.

**Comment by ConnerOrth** [comment]
@rochakgupta regarding your twitter suggestion:
[](https://twitter.com/conner_orth/status/1154723522729709568)

**Comment by rochakgupta** [comment]
Thanks!
