### ISSUE TITLE
You're barking up the wrong tree.

### ISSUE THREAD

**Issue by roothorick** [1995parham/github-do-not-ban-us#90]
This is not an independent interpretation of US law by GitHub. They have been in direct contact with US regulators:

> It also claims to be in discussions with US regulators about how to rectify the situation. 

[Source](https://www.zdnet.com/article/github-starts-blocking-developers-in-countries-facing-us-trade-sanctions/)

The restrictions are a result of direct pressure from the US government. The alternative for GitHub, at this stage, is to get shut down completely, fined, and potentially its higher staff facing criminal charges.

Their hands are tied. You should be protesting to the US government itself.

**Comment by BelegCuthalion** [comment]
That's why I suggested to change the demand

> I agree with @aw3stin1 @PurHur.
> I don't blame Github–or any other company–for giving service to anyone they want, based on nationality, residence, ethnicity, gender, wealth, criminal record, anything. It's their service, they do whatever they want with it.
> I just can't tolerate them acting like freedom knights protecting inclusion and diversity.
> Nor I want to hear a US official claim "sanctions are not affecting ordinary civilians" and "we are not restricting the free flow of communication and information", without any concern of being questioned.
> 
> So my suggestion is still there: Demand Github to either:
> 
>     * release our code, or
> 
>     * announce their decision publicly
>       So at least they can't benefit from their appeal anymore.


#38

**Comment by ovflowd** [comment]
Agreed. Discussing here is no good. But people when they are angry... They don't think twice, right? 😓
