### ISSUE TITLE
Use an alternative like GitFoo.com ?

### ISSUE THREAD

**Issue by Alir3z4** [1995parham/github-do-not-ban-us#913]
This is something that outrageous but it was matter of when and not if. It was first gitlab due to GCP and the rest could follow.

However, due to such sanctions, like many other parts of the country that are or trying to move to a more local and independence flow, a source code sharing should be done as well.

Something like sharing code based on git/etc should not be a big issue and I understand building a community around it would be tough, but it's much better than staying in a hostile environment that can take things that have been given to you as hostage.

Just wanted to let this here and know what others think about it.
I have enough resources and funding to have an alternative service setup and operational for Iranian developers, it's at https://gitfoo.com/explore/repos

I have done enough testing and moved some of my open source code to there and so far it works as expected and has enough features to not let you miss Github for a while.

@1995parham if you think, it's noteworthy, feel free to include it in the readme file to mention as an alternative.

ps: Thanks for making such repo and making others aware <3

**Comment by mmahmoudian** [comment]
Thanks for the effort, but there are few things that are not up the standard I'm looking for.Your solution, inspite of being opensource, has so many moving parts and it has direct link to USA:

1. According to your [Github](https://github.com/Alir3z4) and [GitFoo](https://gitfoo.com/Alir3z4) profiles, you are resident of Russia (**Figure01**)
2. According to **Figure02**, your server is in France
2. According to **Figure02**, the place that provides internet to your server is a company named "Choopa, LLC" which is under "Vultr Holdings, LLC (vultr.com)". By checking them out in [host.io](https://host.io/vultr.com) we can see the location of this company which is USA (**Figure03**)

Therefore your solution is spread in 3 continents, 3 countries, three of which are not in good terms!

I personally appreciate the effort and what you have done is way more than most of us have done to tackle this situation, but your suggested solution can backfire imho.



**Figure01**
![20190729-1422](https://user-images.githubusercontent.com/390889/62044839-8effef00-b20c-11e9-8ac8-8e86d3a69a3e.png)


**Figure02**
![20190729-1418](https://user-images.githubusercontent.com/390889/62044648-23b61d00-b20c-11e9-8d3a-3a8eb2a7707d.png)


**Figure03**
![20190729-1423](https://user-images.githubusercontent.com/390889/62045003-e900b480-b20c-11e9-8632-fb80adc2436e.png)

**Comment by Alir3z4** [comment]
I fully understand your concerns, those are pretty much accurate figures too, however the country of residence doesn't enforce me to obey such sanctions and I'm free to choose to who do "business" with (_as far as my local country law allows_), as of now, even if there is, still there's no trade or business conducted with any sanctioned countries in listed in OFAC, when it's the time to do so I'm fine with moving servers to such location if necessary. We're developers, why do premature optimizations anyway :)

**Comment by Alir3z4** [comment]
Hey @1995parham any reason why such proposal has been closed ?

This is still an alternative to host public/private repositories for anyone that may need such place while other proposal on this repo has not gotten to a definitive or practical phase.

Anyway, it's your call ;)

**Comment by 1995parham** [comment]
@Alir3z4 I have closed some proposals and add their links as alternatives into [README.md](https://github.com/1995parham/github-do-not-ban-us#alternatives).

**Comment by Alir3z4** [comment]
Oh nice, I didn't noticed it, having in the readme seems to be a better way.

Thanks and keep up the good work <3
