### ISSUE TITLE
Update Linked article

### ISSUE THREAD

**Issue by pi0** [1995parham/github-do-not-ban-us#917]
@Hameds just published a new article:

[Yellow badges are back. This time not by Nazi Germany & not for Jews, but by U.S. tech companies](https://medium.com/@hamed/yellow-badges-are-back-this-time-not-by-nazi-germany-not-for-jews-but-by-u-s-tech-companies-48e92d690176)

It has more updated details.

**Comment by pi0** [comment]
Also /cc @Hameds maybe you can link articles to each other and also mention this repository somewhere :)

**Comment by Hameds** [comment]
@pi0 There is a link to this repo in the first article. It's almost 2 A.M. I will update the second article tomorrow
