### ISSUE TITLE
Support from the Netherlands 🇳🇱

### ISSUE THREAD

**Issue by Gusted** [1995parham/github-do-not-ban-us#940]
Even our goverment (Netherlands) visited last 2 weeks the goverment of US. I don't support that github is doing this and if i never saw this repo I will never heard of. Let's do this and maybe bring this even to court this just racism based of nationality from US Goverment!

**Comment by gusbemacbe** [comment]
Too bad that the Nertherlands is an ally of the US and comply to US laws to sanction against Iranian users.

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
