### ISSUE TITLE
Support from Morocco

### ISSUE THREAD

**Issue by Jinzulen** [1995parham/github-do-not-ban-us#962]
OSS is for everyone, it connects people beyond politics, beyond religion, beyond nationality... it must not be polluted by politics. This is disgraceful.

I hope you guys can eventually obtain backups of your work and find a better Git solution in the future, one that isn't subject to anyone's political whims.

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
