### ISSUE TITLE
过分了

### ISSUE THREAD

**Issue by DaZiYuan** [1995parham/github-do-not-ban-us#975]
水能载舟亦能覆舟，如果github是政府的工具，那么社区迟早有一天会用一个新的工具代替你

**Comment by DaZiYuan** [comment]
github上面有全人类贡献的结晶，你可以过滤色情，暴力。但是成为政府的走狗，不能忍

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
