### ISSUE TITLE
Powerful China is Coming！

### ISSUE THREAD

**Issue by Luyao1271** [1995parham/github-do-not-ban-us#978]
Dear Iranian friends, we have seen the news and joined in the struggle of developers. We must fight for our rights!

**Comment by abrahamgreyson** [comment]
你可以表达自己的支持，但是取这样的标题太招黑了吧。 
别人在争取平等权利，跟你是否强大有个毛关系。

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
